name: Feature Request
description: Suggest an idea for Ciyu
title: "[FR] "
labels: feature

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Describe your suggested feature and the main use cases.
      placeholder: Describe the feature here...
    validations:
      required: true

  - type: textarea
    id: feature-impact
    attributes:
      label: Impact
      description: What types of users can benefit from using the suggested feature?
      placeholder: Write the impact here...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add context here...
